version: '3'

services:
  node:
    build: ${COMPOSE_PROJECT_ROOT}/containers/node
    volumes:
      - ${COMPOSE_PROJECT_ROOT}/mnt/node:/src:cached
    ports:
      - 3000:3000 # for ng serve
    working_dir: /src
    tty: true
  